DROP TABLE IF EXISTS admin;

CREATE TABLE admin(
	admin_id INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	number VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
)engine = InnoDB;