DROP TABLE IF EXISTS employee;

CREATE TABLE employee(
	employee_id INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	number VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL
)engine = InnoDB;