DROP TABLE IF EXISTS Product;

CREATE TABLE Product (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	price DECIMAL NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	category VARCHAR(255) NOT NULL,
	introduction VARCHAR(255) NOT NULL
)Engine=InnoDB